### ISSUE TITLE
cvs cv output limits

### ISSUE THREAD

**Issue by ssj71** [blablack/ams-lv2#25]
cvs.ttl shows that the cv controls have a range of 0 to 5 but the cv output port has min and max value of -1 to 1. 

I'm trying to figure out what the ranges of cv ports are expected to be for my own plugins.
Thanks!

**Comment by blablack** [comment]
each output can go from -0.5 to 5.5 (CV from 0 to 5 + Fine from -0.5 to 0.5.

So that's a bug in my ttl definition.

**Comment by ssj71** [comment]
good to know. Is there any standard of what cv's should be? I know moog did the 1v per octave thing, but for lv2? I guess the real question is what should be the cv bounds of my envelope follower ouptut?

**Comment by blablack** [comment]
For an envelope, I guess it should be 0 to 1:
- 0 for fully closed
- 1 for fully opened

that's how the ones in AMS and ams.lv2 work.

**Comment by ssj71** [comment]
perfect. Thats what I wanted to know. Thank you!
