### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by elverskog** [blablack/ams-lv2#26]
I'm seeing this issue when running ./waf. The configuration went fine with no missing dependencies. I tried direct clone from Github and downloading the last 2 releases from your wordpress page.

Build failed
 -> task in 'absolute.ttl' failed (exit status '/home/ee/Downloads/source/ams-lv2-1.1.0/build/ams.lv2/absolute.ttl'): 
	{task 140523753960616: absolute.ttl absolute.ttl -> absolute.ttl}
''
 -> task in 'ad_2.ttl' failed (exit status '/home/ee/Downloads/source/ams-lv2-1.1.0/build/ams.lv2/ad_2.ttl'): 
	{task 140523753960728: ad_2.ttl ad_2.ttl -> ad_2.ttl}
''

**Comment by blablack** [comment]
@elverskog are you still encountering this issue?

**Comment by InTheMorning** [comment]
I am also encountering this issue on Arch.

https://gist.github.com/InTheMorning/8ae90ccf40abe0118900#file-gistfile1-txt

**Comment by blablack** [comment]
This is very strange and I am not sure what is happening!
The first step of the compilation is to copy the ttl files into the build folder.

Maybe if you could use -vvv when compiling we may get more information why it is failing.

**Comment by InTheMorning** [comment]
https://gist.github.com/InTheMorning/2a606cbd6d5376730145

https://gist.github.com/InTheMorning/5bf7374576275f0480aa

**Comment by blablack** [comment]
The issue is with Python3 - I just pushed a modification that should fix it.
Could you test and confirm?

**Comment by InTheMorning** [comment]
It works beautifully, thank you!
