### ISSUE TITLE
Defects in the FFT vocoder

### ISSUE THREAD

**Issue by jpcima** [blablack/ams-lv2#32]
Trying to implement a simple LV2 hosting app I hit an issue with the vocoder plugin, and I found some more by taking a quick glance at the [source code](https://github.com/blablack/ams-lv2/blob/master/src/fftvocoder.cpp).

1. by instanciating the effect and destroying the instance right away, the program will likely crash, because the pointers freed were never set to NULL in the initialization.
2. the instance allocates buffers and plans for FFTW, which it never frees.

Also these are not defects, but still puzzle me a bit
- is there a motivation to prefer FFTW double precision routines over single precision (fftwf_ prefix) ?
- the FFT size is set according to the frame count of the first run, why not query the host's buffer size instead? [buf-size extension](http://lv2plug.in/ns/ext/buf-size/)

**Comment by blablack** [comment]
Closed after merge
