### ISSUE TITLE
Plugin output ports are CV

### ISSUE THREAD

**Issue by artfwo** [blablack/ams-lv2#35]
Is it okay that every plugin in the bundle exposes output ports as CV? LV2 spec is vague about this, but at least it's not recommended: http://lv2plug.in/ns/lv2core/#CVPort

**Comment by blablack** [comment]
It does yes, depending on the plugin itself.
For example a LFO output is definitely CV as it is meant to control other
plugins.

**Comment by artfwo** [comment]
Right. I've actually noticed this problem in noise2. Is noise also supposed to work as CV source?
https://github.com/blablack/ams-lv2/blob/master/ams.lv2/noise2.ttl#L60

**Comment by blablack** [comment]
Noise2 can be used as both:
- noise audio output
- to control other plugins (FM modulation for example)

In ams-lv2, the code for Audio/CV is exactly the same - in the example of
Noise2 the hypothetical 2 versions for CV or Audio output would be exactly
the same but for the port type...

**Comment by artfwo** [comment]
Right, but if a host follows the LV2 recommendation to prevent the user from connection CV out to an audio in, noise2 will be not usable for audio synthesis?

**Comment by blablack** [comment]
Probably not... AFAIK the only host for the ams-lv2 is Ingen, developed by
the developer of LV2 himself, and it all works fine there ☺️

**Comment by artfwo** [comment]
Ok, thanks for clarification, I'll close the issue then!
